### ISSUE TITLE
apa ini sun? 

### ISSUE THREAD

**Issue by ridlo** [ismailsunni/earthquake-ppp#1]
boleh tahu apa ini sun? haha

**Comment by ismailsunni** [comment]
@ridlo tugas kuliah din, explorasi data gempa bumi pakai plannar point pattern hahaha

**Comment by ridlo** [comment]
aku pernah coba plot korelasi gempa dengan fase bulan Sun, sprtinya menarik.. (memang ada papernya sie)

plannar point pattern itu apa an ya? haha

**Comment by ismailsunni** [comment]
@ridlo biasane disingkat PPP din, kayak parpol ahahha... kurang lebih sih analisa buat nyari model di data dua dimensi yg berupa titik, bisa digabung sama parameeter macem2 juga sih misale temporal

**Comment by ridlo** [comment]
kyk buat sidik jari ya, di astronomi juga mungkin dipake, buat combine 2 citra atau untuk tahu citranya ke arah mana dari database citra lain.. (bintang2 sebagai titik2 bepola)

**Comment by ismailsunni** [comment]
Mungkin lebih ke modelling sih din, sama ngeliat trend atau analisis data. Cuman kalau ini ada faktor lokasi.
Kalau sidik jari bukan e lebih ke identifikasi ya?
